name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Execute all unit tests in the project
    - name: Run Parser tests
      run: dotnet test Tests/ParserTests/ParserTests.csproj
    - name: Run LibraryManager tests
      run: dotnet test Tests/LibraryManagerTests/LibraryManagerTests.csproj